// Helper function to get main image (backward compatibility)
function getMainImage(product) {
    return Array.isArray(product.images) ? product.images[0] : product.image;
}

// Database sản phẩm vợt cầu lông
const productsData = {
    yonex: [
        {
            id: "Y001-3U",
            name: "Yonex Astrox 100ZZ",
            brand: "Yonex",
            price: 4500000,
            originalPrice: 5200000,
            images: [
                "img/Yonex/astrox100zz_kurenai.webp",
                "img/Yonex/ax100zz-01-03.webp",
                "img/Yonex/ax100zz-05.webp",
            ],
            description: "Vợt tấn công mạnh mẽ, công nghệ Rotational Generator System. Phiên bản 3U (88g) cho lực smash cực mạnh.",
            weight: "3U",
            stock: 15,
            weightGrams: 88,
            balance: "Nặng đầu",
            flexibility: "Siêu Cứng",
            maxTension: "30 lbs",
            madeIn: "Japan",
            category: "Tấn công",
            rating: 4.9
        },
        {
            id: "Y001-4U",
            name: "Yonex Astrox 100ZZ",
            brand: "Yonex",
            price: 4500000,
            originalPrice: 5200000,
            images: [
                "img/Yonex/astrox100zz_kurenai.webp",
                "img/Yonex/ax100zz-01-03.webp",
                "img/Yonex/ax100zz-05.webp",
            ],
            description: "Vợt tấn công mạnh mẽ. Phiên bản 4U (83g) cân bằng giữa lực và tốc độ.",
            weight: "4U",
            stock: 15,
            weightGrams: 83,
            balance: "Nặng đầu",
            flexibility: "Siêu Cứng",
            maxTension: "30 lbs",
            madeIn: "Japan",
            category: "Tấn công",
            rating: 4.9
        },
        {
            id: "Y002-4U",
            name: "Yonex Arcsaber 11 Pro",
            brand: "Yonex",
            price: 4200000,
            originalPrice: 4800000,
            images: [
                "img/Yonex/arc11-main.webp",
                "img/Yonex/arc11-stick2.webp",
                "img/Yonex/arc11-stickwebp.webp",
            ],
            description: "Vợt cân bằng hoàn hảo giữa tấn công và phòng thủ",
            weight: "4U",
            stock: 15,
            weightGrams: 83,
            balance: "Cân bằng",
            flexibility: "Trung bình",
            maxTension: "28 lbs",
            madeIn: "Japan",
            category: "Đa năng",
            rating: 4.8
        },
        {
            id: "Y002-3U",
            name: "Yonex Arcsaber 11 Pro",
            brand: "Yonex",
            price: 4200000,
            originalPrice: 4800000,
            images: [
                "img/Yonex/arc11-main.webp",
                "img/Yonex/arc11-stick2.webp",
                "img/Yonex/arc11-stickwebp.webp",
            ],
            description: "Vợt cân bằng hoàn hảo giữa tấn công và phòng thủ",
            weight: "3U",
            stock: 15,
            weightGrams: 87,
            balance: "Cân bằng",
            flexibility: "Trung bình",
            maxTension: "28 lbs",
            madeIn: "Japan",
            category: "Đa năng",
            rating: 4.8
        },
        {
            id: "Y003-2U",
            name: "Yonex ISOMETRIC TR1",
            brand: "Yonex",
            price: 1359000,
            originalPrice: 1630000,
            images: [
                "img/Yonex/iso-tr1_blue.webp",
            ],
            description: "Vợt cầu lông Yonex ISOMETRIC TR1 chính hãng là sản phẩm vợt nặng chuyên dụng cho tập cổ tay với trọng lượng 118g hoàn hảo giúp lực tay của bạn khỏe lên từng ngày.",
            weight: "2U",
            stock: 15,
            weightGrams: 118,
            balance: "Cân bằng",
            flexibility: "Trung bình",
            maxTension: "30 lbs",
            madeIn: "Japan",
            category: "Tấn công",
            rating: 4.8
        },
        {
            id: "Y004-5U",
            name: "Yonex Nanoflare 800",
            brand: "Yonex",
            price: 3800000,
            originalPrice: 4200000,
            images: [
                "img/Yonex/nanoflare-800p_269-1.webp"
            ],
            description: "Nhanh nhẹn, xử lý cầu tốc độ cao. Phiên bản 5U siêu nhẹ.",
            weight: "5U",
            stock: 15,
            weightGrams: 78,
            balance: "Nhẹ đầu",
            flexibility: "Mềm",
            maxTension: "27 lbs",
            madeIn: "Japan",
            category: "Tốc độ",
            rating: 4.6
        },
        {
            id: "Y005-2U",
            name: "Yonex Duora Z-Strike",
            brand: "Yonex",
            price: 4709000,
            originalPrice: 5650000,
            images: [
                "img/Yonex/duo-zs.webp"
            ],
            description: "Yonex Duora Z-Strike nổi trội là một trong những cây vợt thành công nhất của nhà Yonex cho lối chơi toàn diện, chớp thời cơ tấn công nhanh chớp nhoáng khiến đối thủ sân bạn không kịp trở tay.",
            weight: "2U",
            stock: 15,
            weightGrams: 93,
            balance: "Hơi nặng đầu",
            flexibility: "Siêu cứng",
            maxTension: "29 lbs",
            madeIn: "Japan",
            category: "Đa Năng",
            rating: 4.6
        },
        {
            id: "Y005-3U",
            name: "Yonex Duora Z-Strike",
            brand: "Yonex",
            price: 4709000,
            originalPrice: 5650000,
            images: [
                "img/Yonex/duo-zs.webp"
            ],
            description: "Yonex Duora Z-Strike nổi trội là một trong những cây vợt thành công nhất của nhà Yonex cho lối chơi toàn diện, chớp thời cơ tấn công nhanh chớp nhoáng khiến đối thủ sân bạn không kịp trở tay.",
            weight: "2U",
            stock: 15,
            weightGrams: 89,
            balance: "Hơi nặng đầu",
            flexibility: "Siêu cứng",
            maxTension: "29 lbs",
            madeIn: "Japan",
            category: "Đa Năng",
            rating: 4.6
        },
        {
            id: "Y006-4U",
            name: "Yonex Astrox 99 Pro",
            brand: "Yonex",
            price: 4400000,
            originalPrice: 5000000,
            images: [
                "img/Yonex/axtrox99pro.webp",
                "img/Yonex/all_3ax99-p_530-2.webp",
                "img/Yonex/all_3ax99-p_530-3.webp",
            ],
            description: "Vợt tấn công của tay vợt số 1 thế giới Kento Momota",
            weight: "4U",
            stock: 15,
            weightGrams: 83,
            balance: "Nặng đầu",
            flexibility: "Cứng",
            maxTension: "30 lbs",
            madeIn: "Japan",
            category: "Tấn công",
            rating: 4.9
        },
        {
            id: "Y007-4U",
            name: "Yonex Nanoray GlanZ",
            brand: "Yonex",
            price: 3079000,
            originalPrice: 3694800,
            images: [
                "img/Yonex/nr-gz.webp"
            ],
            description: "Vợt cầu lông Yonex Nanoray GlanZ là cây vợt cao cấp trong dòng Nanoray của Yonex với những chất liệu và công nghệ đặc biệt dành riêng cho dòng vợt này.",
            weight: "4U",
            stock: 15,
            weightGrams: 85,
            balance: "Cân bằng",
            flexibility: "Trung bình",
            maxTension: "29 lbs",
            madeIn: "Đài loan",
            category: "Đa Năng",
            rating: 4.6
        },
    ],
    lining: [
        {
            id: "L001-3U",
            name: "Lining Aeronaut 9000",
            brand: "Lining",
            price: 4200000,
            originalPrice: 4800000,
            images: [
                "img/Lining/Lining Aeronaut 9000/Lining.png",
                "img/Lining/LiningLining Aeronaut 9000/OP1.png ",
                "img/Lining/LiningLining Aeronaut 9000/OI2.png",
            ],
            description: "Vợt cao cấp nhất của Lining với công nghệ Wing Stabilizer",
            weight: "3U",
            stock: 15,
            weightGrams: 88,
            balance: "Nặng đầu",
            flexibility: "Cứng",
            maxTension: "32 lbs",
            madeIn: "China",
            category: "Tấn công",
            rating: 4.8
        },
        {
            id: "L001-4U",
            name: "Lining Aeronaut 9000",
            brand: "Lining",
            price: 4200000,
            originalPrice: 4800000,
            images: [
                "img/Lining/Lining Aeronaut 9000/Lining.png",
                "img/Lining/Lining Aeronaut 9000/OP1.png",
                "img/Lining/Lining Aeronaut 9000/OI2.png"
            ],
            description: "Vợt cao cấp của Lining. Phiên bản 4U nhẹ và nhanh hơn.",
            weight: "4U",
            stock: 15,
            weightGrams: 83,
            balance: "Nặng đầu",
            flexibility: "Cứng",
            maxTension: "32 lbs",
            madeIn: "China",
            category: "Tấn công",
            rating: 4.8
        },
        {
            id: "L003-4U",
            name: "Lining N99",
            brand: "Lining",
            price: 3500000,
            originalPrice: 4000000,
            images: [
                "img/Lining/Lining N99/vot-cau-long-lining-n99-blue-chinh-hang-2.webp",
                "img/Lining/Lining N99/vot-cau-long-lining-n99-blue-2.webp",
                "img/Lining/Lining N99/vot-lining-air-stream-N99-than-1.webp",
            ],
            description: "Vợt của Lin Dan, kiểm soát và tấn công hoàn hảo",
            weight: "4U",
            stock: 15,
            weightGrams: 83,
            balance: "Cân bằng",
            flexibility: "Trung bình",
            maxTension: "30 lbs",
            madeIn: "China",
            category: "Đa năng",
            rating: 4.8
        },
        {
            id: "L004-5U",
            name: "Lining Windstorm 78",
            brand: "Lining",
            price: 3200000,
            originalPrice: 3700000,
            images: [
                "img/Lining/Windstorm 78/BLACKGOLD1_c4d85e21-31d7-4207-8c12-afbe11698868.webp",
                "img/Lining/Windstorm 78/buy-lining-windstorm-78-black-badminton.webp",
                "img/Lining/Windstorm 78/li-ning-6630-6035292-4.webp",
            ],
            description: "Tốc độ swing nhanh với công nghệ Aerotec-Beam System",
            weight: "5U",
            stock: 15,
            weightGrams: 78,
            balance: "Nhẹ đầu",
            flexibility: "Mềm",
            maxTension: "28 lbs",
            madeIn: "China",
            category: "Tốc độ",
            rating: 4.5
        },
        {
            id: "L005-4U",
            name: "Lining 3D Calibar 900",
            brand: "Lining",
            price: 4000000,
            originalPrice: 4500000,
            images: [
                "img/Lining/3D Calibar 900/74d67d9d-901e-4e24-a6eb-1bad9ec381d6_2048x2048.webp",
                "img/Lining/3D Calibar 900/3efbcdf0-03ea-42c7-965c-cccbfe3e3c53_x700.webp",
                "img/Lining/3D Calibar 900/images-007001481-48915_4.j",
            ],
            description: "Khung vợt 3D độc đáo, tăng vùng ngọt khi đánh",
            weight: "4U",
            stock: 15,
            weightGrams: 83,
            balance: "Cân bằng",
            flexibility: "Trung bình",
            maxTension: "30 lbs",
            madeIn: "China",
            category: "Đa năng",
            rating: 4.7
        }
    ],
    victor: [
        {
            id: "V001-3U",
            name: "Victor Thruster K Falcon",
            brand: "Victor",
            price: 4100000,
            originalPrice: 4700000,
            images: [
                "img/Victor/Thruster K Falcon/808911356889995269.jpg",
                "img/Victor/Thruster K Falcon/OIP (1).jpg",
                "img/Victor/Thruster K Falcon/OIP.jpg",
            ],
            description: "Vợt của Axelsen, công nghệ PYROFIL độc quyền",
            weight: "3U",
            stock: 15,
            weightGrams: 88,
            balance: "Nặng đầu",
            flexibility: "Cứng",
            maxTension: "32 lbs",
            madeIn: "Taiwan",
            category: "Tấn công",
            rating: 4.9
        },
        {
            id: "V001-4U",
            name: "Victor Thruster K Falcon",
            brand: "Victor",
            price: 4100000,
            originalPrice: 4700000,
            images: [
                "img/Victor/Thruster K Falcon/T1.jpg",
                "img/Victor/Thruster K Falcon/T2.jpg",
                "img/Victor/Thruster K Falcon/T3.jpg"
            ],
            description: "Vợt của Axelsen. Phiên bản 4U cân bằng lực và tốc độ.",
            weight: "4U",
            stock: 15,
            weightGrams: 83,
            balance: "Nặng đầu",
            flexibility: "Cứng",
            maxTension: "32 lbs",
            madeIn: "Taiwan",
            category: "Tấn công",
            rating: 4.9
        },
        {
            id: "V002-5U",
            name: "Victor Auraspeed 90K",
            brand: "Victor",
            price: 3700000,
            originalPrice: 4200000,
            images: [
                "img/Victor/Auraspeed 90K/OIP-2.jpg",
                "img/Victor/Auraspeed 90K/OIP-1.jpg",
                "img/Victor/Auraspeed 90K/OIP.jpg"
            ],
            description: "Tốc độ đỉnh cao với công nghệ Nano Fortify",
            weight: "5U",
            stock: 15,
            weightGrams: 78,
            balance: "Nhẹ đầu",
            flexibility: "Mềm",
            maxTension: "30 lbs",
            madeIn: "Taiwan",
            category: "Tốc độ",
            rating: 4.7
        },
        {
            id: "V003-4U",
            name: "Victor Jetspeed S12",
            brand: "Victor",
            price: 3900000,
            originalPrice: 4400000,
            images: [
                "img/Victor/Jetspeed S12/132_1_6_victor_jetspeed_s12_blue.webp",
                "img/Victor/Jetspeed S12/jetspeeds12_1024x1024.webp",
                "img/Victor/Jetspeed S12/jetspeeds122_1024x1024.webp",
            ],
            description: "Aerodynamic Frame giảm sức cản không khí tối đa",
            weight: "4U",
            stock: 15,
            weightGrams: 83,
            balance: "Cân bằng",
            flexibility: "Trung bình",
            maxTension: "30 lbs",
            madeIn: "Taiwan",
            category: "Đa năng",
            rating: 4.8
        },
        {
            id: "V005-4U",
            name: "Victor Bravesword 12",
            brand: "Victor",
            price: 3500000,
            originalPrice: 4000000,
            images: [
                "img/Victor/Bravesword 12/72c5abfa-a19b-4e8b-b3b6-edb36d4ac189_2048x2048.webp",
                "img/Victor/Bravesword 12/BRS-12-3__71649_1800x1800.webp",
                "img/Victor/Bravesword 12/Victor-Brave-Sword-12.webp",
            ],
            description: "Sword concept, chém cầu mạnh mẽ và chính xác",
            weight: "4U",
            stock: 15,
            weightGrams: 83,
            balance: "Nặng đầu",
            flexibility: "Hơi cứng",
            maxTension: "30 lbs",
            madeIn: "Taiwan",
            category: "Tấn công",
            rating: 4.6
        }
    ],
    mizuno: [
        {
            id: "M001-3U",
            name: "Mizuno Fortius Tour F",
            brand: "Mizuno",
            price: 3900000,
            originalPrice: 4500000,
            images: [
                "img/Mizuno/Fortius Tour F/80109_02-250x250.jpg",
                "img/Mizuno/Fortius Tour F/OIP (2).jpg",
                "img/Mizuno/Fortius Tour F/OIP.jpg",
            ],
            description: "Vợt cao cấp nhất Mizuno với Hot Melt Tech",
            weight: "3U",
            stock: 15,
            weightGrams: 88,
            balance: "Nặng đầu",
            flexibility: "Cứng",
            maxTension: "30 lbs",
            madeIn: "Japan",
            category: "Tấn công",
            rating: 4.7
        },
        {
            id: "M001-4U",
            name: "Mizuno Fortius Tour F",
            brand: "Mizuno",
            price: 3900000,
            originalPrice: 4500000,
            images: [
                "img/Mizuno/Fortius Tour F/80109_02-250x250.jpg",
                "img/Mizuno/Fortius Tour F/OIP (2).jpg",
                "img/Mizuno/Fortius Tour F/OIP.jpg"
            ],
            description: "Vợt cao cấp nhất Mizuno. Phiên bản 4U nhẹ hơn.",
            weight: "4U",
            stock: 15,
            weightGrams: 83,
            balance: "Nặng đầu",
            flexibility: "Cứng",
            maxTension: "30 lbs",
            madeIn: "Japan",
            category: "Tấn công",
            rating: 4.7
        },
        {
            id: "M003-4U",
            name: "Mizuno Caliber Regnas",
            brand: "Mizuno",
            price: 3300000,
            originalPrice: 3800000,
            images: [
                "img/Mizuno/Caliber Regnas/mizuno_caliber_reg_badminton_racket_1538486171_3df34478.jpg",
                "img/Mizuno/Caliber Regnas/vot-cau-long-mizuno-caliber-reg-chu-ky-nozomi-okuhara--1.webp",
                "img/Mizuno/Caliber Regnas/vot-cau-long-mizuno-carliber-vs-tour-1.webp"
            ],
            description: "Độ ổn định cao với công nghệ Sonic Metal",
            weight: "4U",
            stock: 15,
            weightGrams: 83,
            balance: "Nặng đầu",
            flexibility: "Hơi cứng",
            maxTension: "30 lbs",
            madeIn: "Japan",
            category: "Tấn công",
            rating: 4.5
        },
        {
            id: "M004-5U",
            name: "Mizuno Altius 03 Speed",
            brand: "Mizuno",
            price: 3100000,
            originalPrice: 3600000,
            images: [
                "img/Mizuno/Altius 03 Speed/file.png",
                "img/Mizuno/Altius 03 Speed/OIP (1).jpg",
                "img/Mizuno/Altius 03 Speed/PXL_20230424_130233622.webp",
            ],
            description: "Tốc độ cao với trọng lượng cực nhẹ",
            weight: "5U",
            stock: 15,
            weightGrams: 78,
            balance: "Nhẹ đầu",
            flexibility: "Mềm",
            maxTension: "28 lbs",
            madeIn: "China",
            category: "Tốc độ",
            rating: 4.4
        },
        {
            id: "M002-4U",
            name: "Mizuno Fortius Pro",
            brand: "Mizuno",
            price: 3500000,
            originalPrice: 4000000,
            images: [
                "img/Mizuno/Fortius Pro/fortius50swift_ecomm_2000x2000_-02.webp",
                "img/Mizuno/Fortius Pro/OIP.jpg",
                "img/Mizuno/Fortius Pro/vot-cau-long-mizuno-fortius-50-swift-dexd.jpg",
            ],
            description: "Công nghệ Wave Rib Frame độc quyền của Mizuno",
            weight: "4U",
            stock: 15,
            weightGrams: 83,
            balance: "Cân bằng",
            flexibility: "Trung bình",
            maxTension: "29 lbs",
            madeIn: "Japan",
            category: "Đa năng",
            rating: 4.6
        }
    ]
};