// Database sản phẩm vợt cầu lông
const productsData = {
    yonex: [
        {
            id: "Y001-3U",
            name: "Yonex Astrox 100ZZ",
            brand: "Yonex",
            price: 4500000,
            originalPrice: 5200000,
            image: "https://placehold.co/300x300/png?text=Astrox+100ZZ",
            description: "Vợt tấn công mạnh mẽ, công nghệ Rotational Generator System. Phiên bản 3U (88g) cho lực smash cực mạnh.",
            weight: "3U",
            weightGrams: 88,
            balance: "Nặng đầu",
            flexibility: "Cứng",
            maxTension: "30 lbs",
            madeIn: "Japan",
            category: "Tấn công",
            rating: 4.9
        },
        {
            id: "Y001-4U",
            name: "Yonex Astrox 100ZZ",
            brand: "Yonex",
            price: 4500000,
            originalPrice: 5200000,
            image: "https://placehold.co/300x300/png?text=Astrox+100ZZ",
            description: "Vợt tấn công mạnh mẽ. Phiên bản 4U (83g) cân bằng giữa lực và tốc độ.",
            weight: "4U",
            weightGrams: 83,
            balance: "Nặng đầu",
            flexibility: "Cứng",
            maxTension: "30 lbs",
            madeIn: "Japan",
            category: "Tấn công",
            rating: 4.9
        },
        {
            id: "Y002-4U",
            name: "Yonex Arcsaber 11 Pro",
            brand: "Yonex",
            price: 4200000,
            originalPrice: 4800000,
            image: "https://placehold.co/300x300/png?text=Arcsaber+11+Pro",
            description: "Vợt cân bằng hoàn hảo giữa tấn công và phòng thủ",
            weight: "4U",
            weightGrams: 83,
            balance: "Cân bằng",
            flexibility: "Trung bình",
            maxTension: "28 lbs",
            madeIn: "Japan",
            category: "Đa năng",
            rating: 4.8
        },
        {
            id: "Y004-5U",
            name: "Yonex Nanoflare 800",
            brand: "Yonex",
            price: 3800000,
            originalPrice: 4200000,
            image: "https://placehold.co/300x300/png?text=Nanoflare+800",
            description: "Nhanh nhẹn, xử lý cầu tốc độ cao. Phiên bản 5U siêu nhẹ.",
            weight: "5U",
            weightGrams: 78,
            balance: "Nhẹ đầu",
            flexibility: "Mềm",
            maxTension: "27 lbs",
            madeIn: "Japan",
            category: "Tốc độ",
            rating: 4.6
        },
        {
            id: "Y006-4U",
            name: "Yonex Astrox 99 Pro",
            brand: "Yonex",
            price: 4400000,
            originalPrice: 5000000,
            image: "https://placehold.co/300x300/png?text=Astrox+99+Pro",
            description: "Vợt tấn công của tay vợt số 1 thế giới Kento Momota",
            weight: "4U",
            weightGrams: 83,
            balance: "Nặng đầu",
            flexibility: "Cứng",
            maxTension: "30 lbs",
            madeIn: "Japan",
            category: "Tấn công",
            rating: 4.9
        }
    ],
    lining: [
        {
            id: "L001-3U",
            name: "Lining Aeronaut 9000",
            brand: "Lining",
            price: 4200000,
            originalPrice: 4800000,
            image: "https://placehold.co/300x300/png?text=Aeronaut+9000",
            description: "Vợt cao cấp nhất của Lining với công nghệ Wing Stabilizer",
            weight: "3U",
            weightGrams: 88,
            balance: "Nặng đầu",
            flexibility: "Cứng",
            maxTension: "32 lbs",
            madeIn: "China",
            category: "Tấn công",
            rating: 4.8
        },
        {
            id: "L001-4U",
            name: "Lining Aeronaut 9000",
            brand: "Lining",
            price: 4200000,
            originalPrice: 4800000,
            image: "https://placehold.co/300x300/png?text=Aeronaut+9000",
            description: "Vợt cao cấp của Lining. Phiên bản 4U nhẹ và nhanh hơn.",
            weight: "4U",
            weightGrams: 83,
            balance: "Nặng đầu",
            flexibility: "Cứng",
            maxTension: "32 lbs",
            madeIn: "China",
            category: "Tấn công",
            rating: 4.8
        },
        {
            id: "L003-4U",
            name: "Lining N99",
            brand: "Lining",
            price: 3500000,
            originalPrice: 4000000,
            image: "https://placehold.co/300x300/png?text=N99",
            description: "Vợt của Lin Dan, kiểm soát và tấn công hoàn hảo",
            weight: "4U",
            weightGrams: 83,
            balance: "Cân bằng",
            flexibility: "Trung bình",
            maxTension: "30 lbs",
            madeIn: "China",
            category: "Đa năng",
            rating: 4.8
        },
        {
            id: "L004-5U",
            name: "Lining Windstorm 78",
            brand: "Lining",
            price: 3200000,
            originalPrice: 3700000,
            image: "https://placehold.co/300x300/png?text=Windstorm+78",
            description: "Tốc độ swing nhanh với công nghệ Aerotec-Beam System",
            weight: "5U",
            weightGrams: 78,
            balance: "Nhẹ đầu",
            flexibility: "Mềm",
            maxTension: "28 lbs",
            madeIn: "China",
            category: "Tốc độ",
            rating: 4.5
        },
        {
            id: "L005-4U",
            name: "Lining 3D Calibar 900",
            brand: "Lining",
            price: 4000000,
            originalPrice: 4500000,
            image: "https://placehold.co/300x300/png?text=3D+Calibar+900",
            description: "Khung vợt 3D độc đáo, tăng vùng ngọt khi đánh",
            weight: "4U",
            weightGrams: 83,
            balance: "Cân bằng",
            flexibility: "Trung bình",
            maxTension: "30 lbs",
            madeIn: "China",
            category: "Đa năng",
            rating: 4.7
        }
    ],
    victor: [
        {
            id: "V001-3U",
            name: "Victor Thruster K Falcon",
            brand: "Victor",
            price: 4100000,
            originalPrice: 4700000,
            image: "https://placehold.co/300x300/png?text=TK+Falcon",
            description: "Vợt của Axelsen, công nghệ PYROFIL độc quyền",
            weight: "3U",
            weightGrams: 88,
            balance: "Nặng đầu",
            flexibility: "Cứng",
            maxTension: "32 lbs",
            madeIn: "Taiwan",
            category: "Tấn công",
            rating: 4.9
        },
        {
            id: "V001-4U",
            name: "Victor Thruster K Falcon",
            brand: "Victor",
            price: 4100000,
            originalPrice: 4700000,
            image: "https://placehold.co/300x300/png?text=TK+Falcon",
            description: "Vợt của Axelsen. Phiên bản 4U cân bằng lực và tốc độ.",
            weight: "4U",
            weightGrams: 83,
            balance: "Nặng đầu",
            flexibility: "Cứng",
            maxTension: "32 lbs",
            madeIn: "Taiwan",
            category: "Tấn công",
            rating: 4.9
        },
        {
            id: "V002-5U",
            name: "Victor Auraspeed 90K",
            brand: "Victor",
            price: 3700000,
            originalPrice: 4200000,
            image: "https://placehold.co/300x300/png?text=ARS+90K",
            description: "Tốc độ đỉnh cao với công nghệ Nano Fortify",
            weight: "5U",
            weightGrams: 78,
            balance: "Nhẹ đầu",
            flexibility: "Mềm",
            maxTension: "30 lbs",
            madeIn: "Taiwan",
            category: "Tốc độ",
            rating: 4.7
        },
        {
            id: "V003-4U",
            name: "Victor Jetspeed S12",
            brand: "Victor",
            price: 3900000,
            originalPrice: 4400000,
            image: "https://placehold.co/300x300/png?text=JS+S12",
            description: "Aerodynamic Frame giảm sức cản không khí tối đa",
            weight: "4U",
            weightGrams: 83,
            balance: "Cân bằng",
            flexibility: "Trung bình",
            maxTension: "30 lbs",
            madeIn: "Taiwan",
            category: "Đa năng",
            rating: 4.8
        },
        {
            id: "V005-4U",
            name: "Victor Bravesword 12",
            brand: "Victor",
            price: 3500000,
            originalPrice: 4000000,
            image: "https://placehold.co/300x300/png?text=BS+12",
            description: "Sword concept, chém cầu mạnh mẽ và chính xác",
            weight: "4U",
            weightGrams: 83,
            balance: "Nặng đầu",
            flexibility: "Hơi cứng",
            maxTension: "30 lbs",
            madeIn: "Taiwan",
            category: "Tấn công",
            rating: 4.6
        }
    ],
    mizuno: [
        {
            id: "M001-3U",
            name: "Mizuno Fortius Tour F",
            brand: "Mizuno",
            price: 3900000,
            originalPrice: 4500000,
            image: "https://placehold.co/300x300/png?text=Fortius+Tour+F",
            description: "Vợt cao cấp nhất Mizuno với Hot Melt Tech",
            weight: "3U",
            weightGrams: 88,
            balance: "Nặng đầu",
            flexibility: "Cứng",
            maxTension: "30 lbs",
            madeIn: "Japan",
            category: "Tấn công",
            rating: 4.7
        },
        {
            id: "M001-4U",
            name: "Mizuno Fortius Tour F",
            brand: "Mizuno",
            price: 3900000,
            originalPrice: 4500000,
            image: "https://placehold.co/300x300/png?text=Fortius+Tour+F",
            description: "Vợt cao cấp nhất Mizuno. Phiên bản 4U nhẹ hơn.",
            weight: "4U",
            weightGrams: 83,
            balance: "Nặng đầu",
            flexibility: "Cứng",
            maxTension: "30 lbs",
            madeIn: "Japan",
            category: "Tấn công",
            rating: 4.7
        },
        {
            id: "M003-4U",
            name: "Mizuno Caliber Regnas",
            brand: "Mizuno",
            price: 3300000,
            originalPrice: 3800000,
            image: "https://placehold.co/300x300/png?text=Caliber+Regnas",
            description: "Độ ổn định cao với công nghệ Sonic Metal",
            weight: "4U",
            weightGrams: 83,
            balance: "Nặng đầu",
            flexibility: "Hơi cứng",
            maxTension: "30 lbs",
            madeIn: "Japan",
            category: "Tấn công",
            rating: 4.5
        },
        {
            id: "M004-5U",
            name: "Mizuno Altius 03 Speed",
            brand: "Mizuno",
            price: 3100000,
            originalPrice: 3600000,
            image: "https://placehold.co/300x300/png?text=Altius+03",
            description: "Tốc độ cao với trọng lượng cực nhẹ",
            weight: "5U",
            weightGrams: 78,
            balance: "Nhẹ đầu",
            flexibility: "Mềm",
            maxTension: "28 lbs",
            madeIn: "China",
            category: "Tốc độ",
            rating: 4.4
        },
        {
            id: "M002-4U",
            name: "Mizuno Fortius Pro",
            brand: "Mizuno",
            price: 3500000,
            originalPrice: 4000000,
            image: "https://placehold.co/300x300/png?text=Fortius+Pro",
            description: "Công nghệ Wave Rib Frame độc quyền của Mizuno",
            weight: "4U",
            weightGrams: 83,
            balance: "Cân bằng",
            flexibility: "Trung bình",
            maxTension: "29 lbs",
            madeIn: "Japan",
            category: "Đa năng",
            rating: 4.6
        }
    ]
};
