// Database sản phẩm vợt cầu lông
const productsData = {
    yonex: [
        {
            id: "Y001",
            name: "Yonex Astrox 100ZZ",
            brand: "Yonex",
            price: 4500000,
            originalPrice: 5200000,
            image: "https://placehold.co/300x300/png?text=Astrox+100ZZ",
            description: "Vợt tấn công mạnh mẽ, công nghệ Rotational Generator System",
            weight: "4U (83g)",
            balance: "Nặng đầu",
            flexibility: "Cứng",
            maxTension: "30 lbs",
            madeIn: "Japan",
            category: "Tấn công",
            rating: 4.9
        },
        {
            id: "Y002",
            name: "Yonex Arcsaber 11 Pro",
            brand: "Yonex",
            price: 4200000,
            originalPrice: 4800000,
            image: "https://placehold.co/300x300/png?text=Arcsaber+11+Pro",
            description: "Vợt cân bằng hoàn hảo giữa tấn công và phòng thủ",
            weight: "3U (88g)",
            balance: "Cân bằng",
            flexibility: "Trung bình",
            maxTension: "28 lbs",
            madeIn: "Japan",
            category: "Đa năng",
            rating: 4.8
        },
        {
            id: "Y003",
            name: "Yonex Voltric Z-Force II",
            brand: "Yonex",
            price: 3900000,
            originalPrice: 4500000,
            image: "https://placehold.co/300x300/png?text=Voltric+Z-Force+II",
            description: "Sức mạnh smash đỉnh cao với công nghệ Tri-Voltage System",
            weight: "3U (88g)",
            balance: "Nặng đầu",
            flexibility: "Rất cứng",
            maxTension: "30 lbs",
            madeIn: "Japan",
            category: "Tấn công",
            rating: 4.7
        },
        {
            id: "Y004",
            name: "Yonex Nanoflare 800",
            brand: "Yonex",
            price: 3800000,
            originalPrice: 4200000,
            image: "https://placehold.co/300x300/png?text=Nanoflare+800",
            description: "Nhanh nhẹn, xử lý cầu tốc độ cao với công nghệ Sonic Flare System",
            weight: "4U (83g)",
            balance: "Nhẹ đầu",
            flexibility: "Mềm",
            maxTension: "27 lbs",
            madeIn: "Japan",
            category: "Tốc độ",
            rating: 4.6
        },
        {
            id: "Y005",
            name: "Yonex Astrox 88D Pro",
            brand: "Yonex",
            price: 4300000,
            originalPrice: 4900000,
            image: "https://placehold.co/300x300/png?text=Astrox+88D+Pro",
            description: "Phiên bản tấn công của dòng Astrox 88, đánh đập mạnh mẽ",
            weight: "4U (83g)",
            balance: "Nặng đầu",
            flexibility: "Cứng",
            maxTension: "29 lbs",
            madeIn: "Japan",
            category: "Tấn công",
            rating: 4.8
        },
        {
            id: "Y006",
            name: "Yonex Astrox 99 Pro",
            brand: "Yonex",
            price: 4400000,
            originalPrice: 5000000,
            image: "https://placehold.co/300x300/png?text=Astrox+99+Pro",
            description: "Vợt tấn công của tay vợt số 1 thế giới Kento Momota",
            weight: "4U (83g)",
            balance: "Nặng đầu",
            flexibility: "Cứng",
            maxTension: "30 lbs",
            madeIn: "Japan",
            category: "Tấn công",
            rating: 4.9
        },
        {
            id: "Y007",
            name: "Yonex Duora 10",
            brand: "Yonex",
            price: 3500000,
            originalPrice: 4000000,
            image: "https://placehold.co/300x300/png?text=Duora+10",
            description: "Mặt vợt 2 mặt khác nhau, linh hoạt mọi tình huống",
            weight: "3U (88g)",
            balance: "Cân bằng",
            flexibility: "Trung bình",
            maxTension: "28 lbs",
            madeIn: "Japan",
            category: "Đa năng",
            rating: 4.5
        },
        {
            id: "Y008",
            name: "Yonex Nanoray Z-Speed",
            brand: "Yonex",
            price: 3200000,
            originalPrice: 3700000,
            image: "https://placehold.co/300x300/png?text=Nanoray+Z-Speed",
            description: "Tốc độ vượt trội cho lối chơi phản công nhanh",
            weight: "5U (78g)",
            balance: "Nhẹ đầu",
            flexibility: "Mềm",
            maxTension: "26 lbs",
            madeIn: "China",
            category: "Tốc độ",
            rating: 4.4
        },
        {
            id: "Y009",
            name: "Yonex Astrox 77",
            brand: "Yonex",
            price: 3600000,
            originalPrice: 4100000,
            image: "https://placehold.co/300x300/png?text=Astrox+77",
            description: "Cân bằng tốt, phù hợp cho người mới chơi ở level cao",
            weight: "4U (83g)",
            balance: "Cân bằng",
            flexibility: "Trung bình",
            maxTension: "28 lbs",
            madeIn: "China",
            category: "Đa năng",
            rating: 4.5
        },
        {
            id: "Y010",
            name: "Yonex Voltric 80 E-Tune",
            brand: "Yonex",
            price: 3400000,
            originalPrice: 3900000,
            image: "https://placehold.co/300x300/png?text=Voltric+80",
            description: "Công nghệ E-Tune giúp điều chỉnh độ căng dễ dàng",
            weight: "4U (83g)",
            balance: "Nặng đầu",
            flexibility: "Cứng",
            maxTension: "29 lbs",
            madeIn: "Taiwan",
            category: "Tấn công",
            rating: 4.6
        }
    ],
    lining: [
        {
            id: "L001",
            name: "Lining Aeronaut 9000",
            brand: "Lining",
            price: 4200000,
            originalPrice: 4800000,
            image: "https://placehold.co/300x300/png?text=Aeronaut+9000",
            description: "Vợt cao cấp nhất của Lining với công nghệ Wing Stabilizer",
            weight: "4U (83g)",
            balance: "Nặng đầu",
            flexibility: "Cứng",
            maxTension: "32 lbs",
            madeIn: "China",
            category: "Tấn công",
            rating: 4.8
        },
        {
            id: "L002",
            name: "Lining Turbo Charging 75",
            brand: "Lining",
            price: 3800000,
            originalPrice: 4300000,
            image: "https://placehold.co/300x300/png?text=TC+75",
            description: "Công nghệ Dynamic-Optimum Frame tối ưu khung vợt",
            weight: "4U (83g)",
            balance: "Nặng đầu",
            flexibility: "Hơi cứng",
            maxTension: "30 lbs",
            madeIn: "China",
            category: "Tấn công",
            rating: 4.7
        },
        {
            id: "L003",
            name: "Lining N99",
            brand: "Lining",
            price: 3500000,
            originalPrice: 4000000,
            image: "https://placehold.co/300x300/png?text=N99",
            description: "Vợt của Lin Dan, kiểm soát và tấn công hoàn hảo",
            weight: "3U (88g)",
            balance: "Cân bằng",
            flexibility: "Trung bình",
            maxTension: "30 lbs",
            madeIn: "China",
            category: "Đa năng",
            rating: 4.8
        },
        {
            id: "L004",
            name: "Lining Windstorm 78",
            brand: "Lining",
            price: 3200000,
            originalPrice: 3700000,
            image: "https://placehold.co/300x300/png?text=Windstorm+78",
            description: "Tốc độ swing nhanh với công nghệ Aerotec-Beam System",
            weight: "5U (78g)",
            balance: "Nhẹ đầu",
            flexibility: "Mềm",
            maxTension: "28 lbs",
            madeIn: "China",
            category: "Tốc độ",
            rating: 4.5
        },
        {
            id: "L005",
            name: "Lining 3D Calibar 900",
            brand: "Lining",
            price: 4000000,
            originalPrice: 4500000,
            image: "https://placehold.co/300x300/png?text=3D+Calibar+900",
            description: "Khung vợt 3D độc đáo, tăng vùng ngọt khi đánh",
            weight: "4U (83g)",
            balance: "Cân bằng",
            flexibility: "Trung bình",
            maxTension: "30 lbs",
            madeIn: "China",
            category: "Đa năng",
            rating: 4.7
        },
        {
            id: "L006",
            name: "Lining N90 III",
            brand: "Lining",
            price: 3300000,
            originalPrice: 3800000,
            image: "https://placehold.co/300x300/png?text=N90+III",
            description: "Phiên bản nâng cấp của dòng N90 huyền thoại",
            weight: "4U (83g)",
            balance: "Nặng đầu",
            flexibility: "Cứng",
            maxTension: "30 lbs",
            madeIn: "China",
            category: "Tấn công",
            rating: 4.6
        },
        {
            id: "L007",
            name: "Lining Flame N55 III",
            brand: "Lining",
            price: 2900000,
            originalPrice: 3400000,
            image: "https://placehold.co/300x300/png?text=Flame+N55",
            description: "Vợt phù hợp cho người mới bắt đầu chơi tấn công",
            weight: "4U (83g)",
            balance: "Nặng đầu",
            flexibility: "Trung bình",
            maxTension: "28 lbs",
            madeIn: "China",
            category: "Tấn công",
            rating: 4.3
        },
        {
            id: "L008",
            name: "Lining G-Force Pro 2800",
            brand: "Lining",
            price: 3600000,
            originalPrice: 4100000,
            image: "https://placehold.co/300x300/png?text=G-Force+2800",
            description: "Công nghệ G-Force giúp tăng lực đập cầu",
            weight: "4U (83g)",
            balance: "Nặng đầu",
            flexibility: "Hơi cứng",
            maxTension: "31 lbs",
            madeIn: "China",
            category: "Tấn công",
            rating: 4.6
        },
        {
            id: "L009",
            name: "Lining Turbo Charging 20",
            brand: "Lining",
            price: 2500000,
            originalPrice: 3000000,
            image: "https://placehold.co/300x300/png?text=TC+20",
            description: "Entry level của dòng Turbo Charging, phù hợp mới chơi",
            weight: "5U (78g)",
            balance: "Cân bằng",
            flexibility: "Trung bình",
            maxTension: "26 lbs",
            madeIn: "China",
            category: "Đa năng",
            rating: 4.2
        },
        {
            id: "L010",
            name: "Lining Rocks 90",
            brand: "Lining",
            price: 2700000,
            originalPrice: 3200000,
            image: "https://placehold.co/300x300/png?text=Rocks+90",
            description: "Độ bền cao, chịu lực tốt cho người chơi phong trào",
            weight: "4U (83g)",
            balance: "Cân bằng",
            flexibility: "Trung bình",
            maxTension: "28 lbs",
            madeIn: "China",
            category: "Đa năng",
            rating: 4.4
        }
    ],
    victor: [
        {
            id: "V001",
            name: "Victor Thruster K Falcon",
            brand: "Victor",
            price: 4100000,
            originalPrice: 4700000,
            image: "https://placehold.co/300x300/png?text=TK+Falcon",
            description: "Vợt của Axelsen, công nghệ PYROFIL độc quyền",
            weight: "4U (83g)",
            balance: "Nặng đầu",
            flexibility: "Cứng",
            maxTension: "32 lbs",
            madeIn: "Taiwan",
            category: "Tấn công",
            rating: 4.9
        },
        {
            id: "V002",
            name: "Victor Auraspeed 90K",
            brand: "Victor",
            price: 3700000,
            originalPrice: 4200000,
            image: "https://placehold.co/300x300/png?text=ARS+90K",
            description: "Tốc độ đỉnh cao với công nghệ Nano Fortify",
            weight: "5U (78g)",
            balance: "Nhẹ đầu",
            flexibility: "Mềm",
            maxTension: "30 lbs",
            madeIn: "Taiwan",
            category: "Tốc độ",
            rating: 4.7
        },
        {
            id: "V003",
            name: "Victor Jetspeed S12",
            brand: "Victor",
            price: 3900000,
            originalPrice: 4400000,
            image: "https://placehold.co/300x300/png?text=JS+S12",
            description: "Aerodynamic Frame giảm sức cản không khí tối đa",
            weight: "4U (83g)",
            balance: "Cân bằng",
            flexibility: "Trung bình",
            maxTension: "30 lbs",
            madeIn: "Taiwan",
            category: "Đa năng",
            rating: 4.8
        },
        {
            id: "V004",
            name: "Victor Thruster Ryuga",
            brand: "Victor",
            price: 4300000,
            originalPrice: 4900000,
            image: "https://placehold.co/300x300/png?text=TK+Ryuga",
            description: "Phiên bản đặc biệt của Thruster K với màu sắc độc đáo",
            weight: "4U (83g)",
            balance: "Nặng đầu",
            flexibility: "Rất cứng",
            maxTension: "32 lbs",
            madeIn: "Taiwan",
            category: "Tấn công",
            rating: 4.9
        },
        {
            id: "V005",
            name: "Victor Bravesword 12",
            brand: "Victor",
            price: 3500000,
            originalPrice: 4000000,
            image: "https://placehold.co/300x300/png?text=BS+12",
            description: "Sword concept, chém cầu mạnh mẽ và chính xác",
            weight: "4U (83g)",
            balance: "Nặng đầu",
            flexibility: "Hơi cứng",
            maxTension: "30 lbs",
            madeIn: "Taiwan",
            category: "Tấn công",
            rating: 4.6
        },
        {
            id: "V006",
            name: "Victor Hypernano X 900",
            brand: "Victor",
            price: 3300000,
            originalPrice: 3800000,
            image: "https://placehold.co/300x300/png?text=HX+900",
            description: "Công nghệ Nano tăng độ bền và đàn hồi",
            weight: "4U (83g)",
            balance: "Cân bằng",
            flexibility: "Trung bình",
            maxTension: "29 lbs",
            madeIn: "China",
            category: "Đa năng",
            rating: 4.5
        },
        {
            id: "V007",
            name: "Victor Thruster F",
            brand: "Victor",
            price: 3800000,
            originalPrice: 4300000,
            image: "https://placehold.co/300x300/png?text=TK+F",
            description: "Phiên bản Force, tối ưu cho smash cực mạnh",
            weight: "3U (88g)",
            balance: "Nặng đầu",
            flexibility: "Cứng",
            maxTension: "32 lbs",
            madeIn: "Taiwan",
            category: "Tấn công",
            rating: 4.8
        },
        {
            id: "V008",
            name: "Victor Auraspeed Light Fighter",
            brand: "Victor",
            price: 2900000,
            originalPrice: 3400000,
            image: "https://placehold.co/300x300/png?text=ARS+LF",
            description: "Siêu nhẹ chỉ 73g, tốc độ xử lý cực nhanh",
            weight: "6U (73g)",
            balance: "Nhẹ đầu",
            flexibility: "Mềm",
            maxTension: "28 lbs",
            madeIn: "China",
            category: "Tốc độ",
            rating: 4.4
        },
        {
            id: "V009",
            name: "Victor Jetspeed S10",
            brand: "Victor",
            price: 3200000,
            originalPrice: 3700000,
            image: "https://placehold.co/300x300/png?text=JS+S10",
            description: "Cân bằng tốt giữa tốc độ và sức mạnh",
            weight: "4U (83g)",
            balance: "Cân bằng",
            flexibility: "Trung bình",
            maxTension: "29 lbs",
            madeIn: "China",
            category: "Đa năng",
            rating: 4.5
        },
        {
            id: "V010",
            name: "Victor Arrowpower 990",
            brand: "Victor",
            price: 2600000,
            originalPrice: 3100000,
            image: "https://placehold.co/300x300/png?text=AP+990",
            description: "Giá tốt, phù hợp cho người chơi trung bình",
            weight: "4U (83g)",
            balance: "Nặng đầu",
            flexibility: "Trung bình",
            maxTension: "28 lbs",
            madeIn: "China",
            category: "Tấn công",
            rating: 4.3
        }
    ],
    mizuno: [
        {
            id: "M001",
            name: "Mizuno Fortius Tour F",
            brand: "Mizuno",
            price: 3900000,
            originalPrice: 4500000,
            image: "https://placehold.co/300x300/png?text=Fortius+Tour+F",
            description: "Vợt cao cấp nhất Mizuno với Hot Melt Tech",
            weight: "4U (83g)",
            balance: "Nặng đầu",
            flexibility: "Cứng",
            maxTension: "30 lbs",
            madeIn: "Japan",
            category: "Tấn công",
            rating: 4.7
        },
        {
            id: "M002",
            name: "Mizuno Fortius Pro",
            brand: "Mizuno",
            price: 3500000,
            originalPrice: 4000000,
            image: "https://placehold.co/300x300/png?text=Fortius+Pro",
            description: "Công nghệ Wave Rib Frame độc quyền của Mizuno",
            weight: "4U (83g)",
            balance: "Cân bằng",
            flexibility: "Trung bình",
            maxTension: "29 lbs",
            madeIn: "Japan",
            category: "Đa năng",
            rating: 4.6
        },
        {
            id: "M003",
            name: "Mizuno Caliber Regnas",
            brand: "Mizuno",
            price: 3300000,
            originalPrice: 3800000,
            image: "https://placehold.co/300x300/png?text=Caliber+Regnas",
            description: "Độ ổn định cao với công nghệ Sonic Metal",
            weight: "4U (83g)",
            balance: "Nặng đầu",
            flexibility: "Hơi cứng",
            maxTension: "30 lbs",
            madeIn: "Japan",
            category: "Tấn công",
            rating: 4.5
        },
        {
            id: "M004",
            name: "Mizuno Altius 03 Speed",
            brand: "Mizuno",
            price: 3100000,
            originalPrice: 3600000,
            image: "https://placehold.co/300x300/png?text=Altius+03",
            description: "Tốc độ cao với trọng lượng cực nhẹ",
            weight: "5U (78g)",
            balance: "Nhẹ đầu",
            flexibility: "Mềm",
            maxTension: "28 lbs",
            madeIn: "China",
            category: "Tốc độ",
            rating: 4.4
        },
        {
            id: "M005",
            name: "Mizuno Fortius 30 Power",
            brand: "Mizuno",
            price: 2800000,
            originalPrice: 3300000,
            image: "https://placehold.co/300x300/png?text=Fortius+30",
            description: "Giá tốt, phù hợp cho người mới chơi tấn công",
            weight: "4U (83g)",
            balance: "Nặng đầu",
            flexibility: "Trung bình",
            maxTension: "28 lbs",
            madeIn: "China",
            category: "Tấn công",
            rating: 4.2
        },
        {
            id: "M006",
            name: "Mizuno Valour 10",
            brand: "Mizuno",
            price: 2500000,
            originalPrice: 3000000,
            image: "https://placehold.co/300x300/png?text=Valour+10",
            description: "Cân bằng tốt cho người chơi all-round",
            weight: "4U (83g)",
            balance: "Cân bằng",
            flexibility: "Trung bình",
            maxTension: "27 lbs",
            madeIn: "China",
            category: "Đa năng",
            rating: 4.1
        },
        {
            id: "M007",
            name: "Mizuno Fortius 20 Quick",
            brand: "Mizuno",
            price: 2300000,
            originalPrice: 2800000,
            image: "https://placehold.co/300x300/png?text=Fortius+20",
            description: "Tốc độ swing nhanh, phù hợp đánh đôi",
            weight: "5U (78g)",
            balance: "Nhẹ đầu",
            flexibility: "Mềm",
            maxTension: "26 lbs",
            madeIn: "China",
            category: "Tốc độ",
            rating: 4.0
        },
        {
            id: "M008",
            name: "Mizuno Caliber LX",
            brand: "Mizuno",
            price: 3000000,
            originalPrice: 3500000,
            image: "https://placehold.co/300x300/png?text=Caliber+LX",
            description: "Phiên bản nâng cấp với vật liệu cao cấp hơn",
            weight: "4U (83g)",
            balance: "Nặng đầu",
            flexibility: "Cứng",
            maxTension: "30 lbs",
            madeIn: "Japan",
            category: "Tấn công",
            rating: 4.5
        },
        {
            id: "M009",
            name: "Mizuno Altius 01 Feel",
            brand: "Mizuno",
            price: 2700000,
            originalPrice: 3200000,
            image: "https://placehold.co/300x300/png?text=Altius+01",
            description: "Cảm giác đánh cầu tốt, kiểm soát chính xác",
            weight: "4U (83g)",
            balance: "Cân bằng",
            flexibility: "Trung bình",
            maxTension: "28 lbs",
            madeIn: "China",
            category: "Đa năng",
            rating: 4.3
        },
        {
            id: "M010",
            name: "Mizuno Accel Power 800",
            brand: "Mizuno",
            price: 2200000,
            originalPrice: 2700000,
            image: "https://placehold.co/300x300/png?text=Accel+800",
            description: "Entry level tốt cho người mới bắt đầu",
            weight: "4U (83g)",
            balance: "Cân bằng",
            flexibility: "Trung bình",
            maxTension: "26 lbs",
            madeIn: "China",
            category: "Đa năng",
            rating: 3.9
        }
    ]
};

// Export để sử dụng ở file khác
if (typeof module !== 'undefined' && module.exports) {
    module.exports = productsData;
}
